---
application:
  name: "nfcqs-py"
  project: "nfcqs"
  organization: "QoveryCommunity"
  storage:
  - name: "public"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/public"
databases:
- type: "MYSQL"
  name: "nfcqs"
  version: "8.0"
routers:
- name: "main-nfcqs-py"
  routes:
  - application_name: "nfcqs-py"
    paths:
    - "/*"
